
--- Las tablas tienen prefijo A_ para facilitar su acceso desde SQL Developer

-- Creación de la tabla CARNET y especificación de sus restricciones

CREATE TABLE A_CARNET
   (ID NUMBER, 
	IDVISITANTE NUMBER NOT NULL,
	CONSTRAINT A_CARNET_PK PRIMARY KEY (ID));
	
ALTER TABLE A_CARNET
	ADD CONSTRAINT fk_a_visitante
	FOREIGN KEY(idvisitante)
	REFERENCES a_visitante(id)
ENABLE;


-- Creación de la tabla VISITANTE y especificación de sus restricciones

CREATE TABLE A_VISITANTE
   (ID NUMBER, 
	NOMBRE VARCHAR2(255 BYTE) NOT NULL, 
	TIPO VARCHAR2(255 BYTE),
	NUMERO_TELEFONO NUMBER NOT NULL, 
	CORREO VARCHAR2(255 BYTE) NOT NULL,
	NOM_CONTACTO VARCHAR2(255 BYTE),
	NUM_CONTACTO VARCHAR2(255 BYTE),

	CONSTRAINT A_VISITANTE_PK PRIMARY KEY (ID));
	
ALTER TABLE A_VISITANTE
	ADD CONSTRAINT CK_VISIT_TIP
	CHECK (TIPO IN ('Cliente', 'Domiciliario', 'Empleado'))

ENABLE;

-- Creación de la tabla LECTOR y especificación de sus restricciones

CREATE TABLE A_LECTOR
   (ID NUMBER, 
	NUM_VISITANTES NUMBER,
	UBICACION VARCHAR2(255 BYTE) NOT NULL, 

	CONSTRAINT A_LECTOR_PK PRIMARY KEY (ID));

-- Creación de la tabla CENTRO COMERCIALy especificación de sus restricciones

CREATE TABLE A_CENTROCOMERCIAL
   (ID NUMBER, 
	NOMBRE VARCHAR2(255 BYTE) NOT NULL, 
	AFORO_MAX NUMBER,
	NUM_VISITANTES NUMBER

	CONSTRAINT A_CENTROCOMERCIAL_PK PRIMARY KEY (ID));

-- Creación de la tabla LOCAL y especificación de sus restricciones

CREATE TABLE A_LOCAL
   (ID NUMBER, 
	TIPO VARCHAR2(255 BYTE) NOT NULL,
	NOMBRE VARCHAR2(255 BYTE) NOT NULL,
	AFORO_MAX NUMBER,
	UBICACION VARCHAR2(255 BYTE) NOT NULL, 
	ID_CENTROCOMERCIAL NUMBER NOT NULL

	CONSTRAINT A_LOCAL_PK PRIMARY KEY (ID));
	
ALTER TABLE A_LOCAL
	ADD CONSTRAINT fk_a_centrocomercial
	FOREIGN KEY(idcentrocomercial)
	REFERENCES a_centrocomercial(id)
ENABLE;

-- Creación de la tabla CALENDARIO y especificación de sus restricciones

CREATE TABLE A_CALENDARIO
   (ID NUMBER, 
	ANIO NUMBER,
	MES NUMBER,
	DIA NUMBER,
	ID_HORARIO NUMBER

	CONSTRAINT A_CALENDARIO_PK PRIMARY KEY (ID));
	
ALTER TABLE A_CALENDARIO
	ADD CONSTRAINT fk_a_horario
	FOREIGN KEY(idhorario)
	REFERENCES a_horario(id)
ENABLE;

ALTER TABLE A_CALENDARIO
ADD CONSTRAINT ck_a_calendario
CHECK ANIO >= 2020, MES >0, MES<13, DIA > 0
ENABLE;


-- Creaación de la tabla HORARIOy especificación de sus restricciones
CREATE TABLE A_HORARIO 
   (ID NUMBER, 
	HORA_ENTRADA NUMBER, 
	HORA_SALIDA NUMBER, 
	CONSTRAINT A_HORARIO_PK PRIMARY KEY (ID));
	
ALTER TABLE A_HORARIO
ADD CONSTRAINT fk_a_tipobebida
    FOREIGN KEY (idtipobebida)
    REFERENCES a_tipobebida(id)
ENABLE;


-- Creaación de la tabla HORARIO_LOCAL y especificación de sus restricciones
CREATE TABLE A_HORALOCAL
(
  IDHORARIO NUMBER,
  IDLOCAL NUMBER,
 
  CONSTRAINT A_HORALOCAL_PK PRIMARY KEY (IDHORARIO, IDLOCAL);

ALTER TABLE A_HORALOCAL
ADD CONSTRAINT fk_h_horario
    FOREIGN KEY (idhorario)
    REFERENCES a_horario(id)
ENABLE;
    
ALTER TABLE A_HORALOCAL
ADD CONSTRAINT fk_h_local
    FOREIGN KEY (idlocal)
    REFERENCES a_local(id)
ENABLE;

-- Creaación de la tabla CALENDARIO_VISITANTE_LOCAL y especificación de sus restricciones
CREATE TABLE A_CALENDARIO_VISITANTE_LOCAL
(
  IDCALENDARIO NUMBER,
  IDLOCAL NUMBER,
  IDVISITANTE NUMBER
 
  CONSTRAINT A_CALENDARIO_VISITANTE_LOCAL PRIMARY KEY (IDHORARIO, IDLOCAL, IDVISITANTE);

ALTER TABLE CALENDARIO_VISITANTE_LOCAL
ADD CONSTRAINT fk_c_calendario
    FOREIGN KEY (idcalendario)
    REFERENCES a_calendario(id)
ENABLE;
    
ALTER TABLE CALENDARIO_VISITANTE_LOCAL
ADD CONSTRAINT fk_c_local
    FOREIGN KEY (idlocal)
    REFERENCES a_local(id)
ENABLE;

ALTER TABLE CALENDARIO_VISITANTE_LOCAL
ADD CONSTRAINT fk_c_visitante
    FOREIGN KEY (idvisitante)
    REFERENCES a_visitante(id)
ENABLE;

-- Creaación de la tabla CALENDARIO_VISITANTE_CC y especificación de sus restricciones
CREATE TABLE A_CALENDARIO_VISITANTE_CC
(
  IDCALENDARIO NUMBER,
  IDCC NUMBER,
  IDVISITANTE NUMBER
 
  CONSTRAINT A_CALENDARIO_VISITANTE_CC PRIMARY KEY (IDHORARIO, IDLOCAL, IDVISITANTE);

ALTER TABLE CALENDARIO_VISITANTE_CC
ADD CONSTRAINT fk_v_calendario
    FOREIGN KEY (idcalendario)
    REFERENCES a_calendario(id)
ENABLE;
    
ALTER TABLE CALENDARIO_VISITANTE_CC
ADD CONSTRAINT fk_v_cc
    FOREIGN KEY (idcc)
    REFERENCES a_centrocomercial(id)
ENABLE;

ALTER TABLE CALENDARIO_VISITANTE_CC
ADD CONSTRAINT fk_v_visitante
    FOREIGN KEY (idvisitante)
    REFERENCES a_visitante(id)
ENABLE;

-- Creaación de la tabla LECTORLOCAL y especificación de sus restricciones
CREATE TABLE A_LECTORLOCAL
(
  IDLECTOR NUMBER,
  IDLOCAL NUMBER,
 
  CONSTRAINT A_LECTORLOCAL_PK PRIMARY KEY (IDHORARIO, IDLOCAL);

ALTER TABLE A_LECTORLOCAL
ADD CONSTRAINT fk_h_lector
    FOREIGN KEY (idlector)
    REFERENCES a_lector(id)
ENABLE;
    
ALTER TABLE A_LECTORLOCAL
ADD CONSTRAINT fk_h_local
    FOREIGN KEY (idlocal)
    REFERENCES a_local(id)
ENABLE;

-- Creaación de la tabla LECTORCC y especificación de sus restricciones

CREATE TABLE A_LECTORCC
(
  IDLECTOR NUMBER,
  IDCC NUMBER,
 
  CONSTRAINT A_LECTORCC_PK PRIMARY KEY (IDHORARIO, IDCC);

ALTER TABLE A_LECTORCC
ADD CONSTRAINT fk_h_lector
    FOREIGN KEY (idlector)
    REFERENCES a_lector(id)
ENABLE;
    
ALTER TABLE A_LECTORCC
ADD CONSTRAINT fk_h_local
    FOREIGN KEY (idlocal)
    REFERENCES a_local(id)
ENABLE;

COMMIT;